#!/bin/bash

if ! shopt -q login_shell; then
    echo "Restarting $0 as login shell script"
    exec bash -l $0 "$@"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# X resources
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# turn bell off
xset -b

# US-Intl. AltGr layout, Caps is Ctrl, Menu is Compose
setxkbmap -layout us -variant altgr-intl -option ctrl:nocaps -option compose:menu

# Make useless <> key useful
# xmodmap -e "keycode 94 = Super_L Super_L Super_L"
# xmodmap -e "add mod4 = Super_L"
# Fix stupid xlock killer anti-feature
xmodmap -e "keycode 63 = KP_Multiply NoSymbol KP_Multiply NoSymbol"
xmodmap -e "keycode 106 = KP_Divide NoSymbol KP_Divide NoSymbol"

# Load icc profile
[ -f ~/.dotfiles/icc/current.icc ] && xcalib ~/.dotfiles/icc/current.icc

#ssh agent
eval $(ssh-agent)

#gpg agent
hash gpg-agent 2> /dev/null && eval $(gpg-agent --daemon)

#export CHROMIUM_USER_FLAGS=--audio-buffer-size=2048:${CHROMIUM_USER_FLAGS}

pulseaudio -D
mount-tray &

exec $1
