#!/bin/bash

if ! shopt -q login_shell; then
    echo "Restarting $0 as login shell script"
    exec bash -l $0 "$@"
fi

# arch
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -f /etc/X11/Xsession ]; then
  # ubuntu lightdm. /etc/X11/Xsession sources ~/.xsessionrc and spawns all necessary processes AND starts WM
  source /etc/X11/Xsession
else 
  # arch slim
  [ -f ~/.xsessionrc ] && source ~/.xsessionrc
  exec $1
fi
